#!/usr/bin/env bash
# script to configure server to redirect to
# another page

# Set up 301 redirection for /redirect_me using sed
sudo sed -i '/^}$/i \
    location \/redirect_me {\
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# Restart Nginx to apply the server
sudo service nginx restart
