#!/usr/bin/env bash
# Displays time for 12 hrs 59 mins
# 	   Displays hrs from 0 -12
#	   Displays mins from 0 - 59

hour="0"

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
	echo "$minute"
	(( minute++ ))
    done
    (( hour++ ))
done
