#!/usr/bin/env bash
# Script that configures an Ubuntu server
# +Reqments: localhost resoleves to 127.0.0.2
# + facebook.con resolves to 8.8.8.8

cp /etc/hosts ~/hosts/new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
