#!/usr/bin/env bash
# debug container to run Nginx as nginx
sudo pkill apache2
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo service nginx start
